/*
 * UC4
 * This is the Course API for UC4.
 *
 * OpenAPI spec version: 0.1.4
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.upb.cs.uc4.chaincode.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Error
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-06-27T14:59:21.562+02:00")

public class InvalidParams(){
    @SerializedName("name")
    private String name = null;
  
    @SerializedName("reason")
    private String reason = null;
  
    public InvalidParams name(String name) {
      this.name = name;
      return this;
    }
  
     /**
     * Get name
     * @return name
    **/
    @ApiModelProperty(value = "")
    public String getName() {
      return name;
    }
  
    public void setName(String name) {
      this.name = name;
    }
  
    public InvalidParams reason(String reason) {
      this.reason = reason;
      return this;
    }
  
     /**
     * Get reason
     * @return reason
    **/
    @ApiModelProperty(value = "")
    public String getReason() {
      return reason;
    }
  
    public void setReason(String reason) {
      this.reason = reason;
    }

    @Override
    public boolean equals(Object o) {
      if (this == o) {
        return true;
      }
      if (o == null || getClass() != o.getClass()) {
        return false;
      }
      InvalidParams inavlidParams = (InvalidParams) o;
      return Objects.equals(this.name, inavlidParams.name) &&
          Objects.equals(this.reason, inavlidParams.reason);
    }
  
    @Override
    public int hashCode() {
      return Objects.hash(name, reason);
    }
  
  
    @Override
    public String toString() {
      StringBuilder sb = new StringBuilder();
      sb.append("class InvalidParams {\n");
      
      sb.append("    name: ").append(toIndentedString(name)).append("\n");
      sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
      sb.append("}");
      return sb.toString();
    }
  
    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
      if (o == null) {
        return "null";
      }
      return o.toString().replace("\n", "\n    ");
    }
}