/*
 * UC4
 * This is the User API for UC4.
 *
 * OpenAPI spec version: 0.2.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.upb.cs.uc4.chaincode.model;

import java.util.Objects;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

/**
 * ImmatriculationInterval
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-07-26T19:00:46.792+02:00")



public class MatriculationInterval {
  @SerializedName("firstSemester")
  private String firstSemester = null;

  @SerializedName("lastSemester")
  private String lastSemester = null;

  public MatriculationInterval firstSemester(String firstSemester) {
    this.firstSemester = firstSemester;
    return this;
  }

   /**
   * Get firstSemester
   * @return firstSemester
  **/
  @ApiModelProperty(value = "")
  public String getFirstSemester() {
    return firstSemester;
  }

  public void setFirstSemester(String firstSemester) {
    this.firstSemester = firstSemester;
  }

  public MatriculationInterval lastSemester(String lastSemester) {
    this.lastSemester = lastSemester;
    return this;
  }

   /**
   * Get lastSemester
   * @return lastSemester
  **/
  @ApiModelProperty(value = "")
  public String getLastSemester() {
    return lastSemester;
  }

  public void setLastSemester(String lastSemester) {
    this.lastSemester = lastSemester;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatriculationInterval immatriculationInterval = (MatriculationInterval) o;
    return Objects.equals(this.firstSemester, immatriculationInterval.firstSemester) &&
        Objects.equals(this.lastSemester, immatriculationInterval.lastSemester);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstSemester, lastSemester);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ImmatriculationInterval {\n");
    
    sb.append("    firstSemester: ").append(toIndentedString(firstSemester)).append("\n");
    sb.append("    lastSemester: ").append(toIndentedString(lastSemester)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

