/**
  * UC4
  * This is the API for UC4.
  *
  * OpenAPI spec version: 0.0.1
  * Contact: apiteam@uc4.cs.upb.de
  *
  * NOTE: This class is auto generated by the swagger code generator program.
  * https://github.com/swagger-api/swagger-codegen.git
  * Do not edit the class manually.
  */

package de.upb.cs.uc4.course.model

import de.upb.cs.uc4.course.model.CourseLanguage.CourseLanguage
import de.upb.cs.uc4.course.model.CourseType.CourseType
import play.api.libs.json._

case class Course(
                   courseId: Long,
                   courseName: String,
                   courseType: CourseType,
                   startDate: String,
                   endDate: String,
                   ects: Int,
                   lecturerId: String,
                   maxParticipants: Int,
                   currentParticipants: Int,
                   courseLanguage: CourseLanguage,
                   courseDescription: String
                 )
{
  def trim: Course = {
    copy(
      courseId,
      courseName.trim,
      courseType,
      startDate.trim,
      endDate.trim,
      ects,
      lecturerId.trim,
      maxParticipants,
      currentParticipants,
      courseLanguage,
      courseDescription.trim
    )
  }
}


object Course {
  implicit val format: Format[Course] = Json.format

}

