/**
 * UC4
 * This is the API for UC4.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: apiteam@uc4.cs.upb.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.upb.cs.uc4.model

import play.api.libs.json._

case class ApiResponse (
                  code: Option[Int],
                  `type`: Option[String],
                  message: Option[String]
)

object ApiResponse {
implicit val format: Format[ApiResponse] = Json.format
}

